export const CREATE_TODO = 'CREATE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const MARK_COMPLETE_TODO = 'MARK_COMPLETE_TODO'

export const LOADING_TODOS = 'LOADING_TODOS'
export const LOADING_TODOS_SUCCESS = 'LOADING_TODOS_SUCCESS'
export const LOADING_TODOS_FAILURE = 'LOADING_TODOS_FAILURE'
